language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - cd TP1/lab1
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro    
